version: "3"

services:
  httpd:
    image: "php:8.0.9-apache"
    restart: 'no'
    ports:
      - '${LOCAL_HTTP_PORT}:80'
    volumes:
      - ${LOCAL_DOCUMENT_ROOT}:/var/www
      - ${LOCAL_PHP_INI}:/usr/local/etc/php
      - ${LOCAL_SITES_AVAILABLE}:/etc/apache2/sites-available
    build:
      context: .
      dockerfile: ./Dockerfile
networks: 
  default: 
    name: phpdev

