services:
  httpd:
    image: "php:8.4.1-apache"
    restart: 'no'
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./root:/root
      - .:/var/www
      - ./config/sites-available:/etc/apache2/sites-available
      - ./config/php:/usr/local/etc
    build:
      context: .
      dockerfile: ./Dockerfile
networks: 
  default: 
    name: phpdev

