version: "3"

services:
  httpd:
    image: "php:8.0.9-apache"
    restart: 'no'
    ports:
      - '80:80'
    volumes:
      - .:/var/www
      - ./php_ini:/usr/local/etc/php
      - ./sites-available:/etc/apache2/sites-available
    build:
      context: .
      dockerfile: ./Dockerfile
networks: 
  default: 
    name: phpdev

