services:
  httpd:
    image: "php:8.4.1-apache"
    restart: 'always'
    ports:
      - "8080:80" # Increment 8080 if you run more than one container
      - "5173:5173" # used by node dev server, remove in production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./root:/root
      - .:/var/www
      - ./config/sites-available:/etc/apache2/sites-available
      - ./config/php:/usr/local/etc
    build:
      context: .
      dockerfile: ./Dockerfile
networks: 
  default: 
    name: phpdev

