version: "3"

services:
  httpd:
    image: "php:7.4-apache"
    restart: 'no'
    ports:
      - '${LOCAL_HTTP_PORT}:80'
    volumes:
      - ${LOCAL_DOCUMENT_ROOT}:/var/www
    build:
      context: .
      dockerfile: ./Dockerfile
networks: 
  default: 
    name: phpdev

